### PR TITLE
Adding iOBC UART doc + demo

### PR DESCRIPTION
**Pull request by CatGarab**
Adding doc blurb about the iOBC's UART ports

Also adding UART TX/RX demo program for KubOS Linux

It's not well fleshed out, but it does work, so I want to save this code somewhere accessible for future reference.

### CODE REVIEW

**Comment by CatGarab** [comment]
[iOBC UART communication](https://trello.com/c/2R6R3xOA/61-iobc-uart-communication)

**Comment by plauche** [comment]
Do these programs belong in the `examples` folder, rather than creating a new `demos` folder?

**Comment by CatGarab** [comment]
@plauche Ultimately they could go there, but right now they're rough enough that I don't really want other people to use them. I'd like to come back later and flesh them out with what the options are and how exactly `termio` works in the context of UARTs.

**Comment by CatGarab** [comment]
Cleaned the examples up to a point where I'm happy with them. They have now been migrated to the examples folder

**Pull request merged**
