### PR TITLE
KUBOS-385 Add circleCI integration

### PR DESCRIPTION
**Pull request by kyleparrott**
The PR name says it all.

This is dependent on PR #44 being merged and functional. Once that PR is merged, this can be corrected to run all of the modules for more targets rather than just telemetry for the STM discovery board.

### CODE REVIEW

**Comment by davesims** [comment]
Now that https://github.com/kubostech/kubos/pull/44 is merged, can we move this in after the next release?

**Comment by kyleparrott** [comment]
@davesims There is some more configuration needed to get the full test suite running for the appropriate module and target combinations. 

Since this PR is getting a little bit old, we could merge this and then sometime in the near future revisit the full configuration in a new PR. What do you think?

**Comment by kyleparrott** [comment]
Since this PR had the base of the circle config in it, I added an integration test on top of it.

What's in this PR: 
* A basic Circle CI config that runs a docker mirror of the vagrant development environment
* A slightly modified integration test that was pull from the cli repo (It builds the rt/linux examples for the rt/linux targets, respectively)

**Comment by kyleparrott** [comment]
Friendly Bump for 👀 

cc/ @kubostech/devs

**Pull request merged**
